#!/bin/sh
#############################################################################
###
### Update Adminer to latest version
###
### Run in cron once a day/week to be up-to-date
###
#############################################################################

wget http://www.adminer.org/latest-mysql.php -qO $(dirname $0)/adminer.php
