#! /bin/bash
#############################################################################
### Install script
###
### @author      Knut Kohl <github@knutkohl.de>
### @copyright   2012 Knut Kohl
### @license     MIT License (MIT) http://opensource.org/licenses/MIT
#############################################################################

### echo ...
function es { echo =========================================================; }
function e { es; echo "= $*"; es; }

### Return default value $2, if $1 was empty
function d { [ "$1" ] && echo "$1" || echo "$2"; }

e 'Clone PVLng Github repository'
git clone https://github.com/KKoPV/PVLng.git .
[ $? -eq 0 ] || exit 1

es

read -p "Checkout 'develop' branch for testing [y/N] " input <&1

[ "$input" == Y -o "$input" == y ]  && git checkout develop

e 'Check for Composer ...'
if [ -z "$(which composer)" ]; then
    e 'Missing Composer, please follow https://getcomposer.org/download/ for details'
    exit 1
fi

composer update --no-dev

while [ "$ok" != Y ]; do

    e 'Setup MySQL database'

    dbhost=$(d "$dbhost" localhost)
    read -p "Server (required) [$dbhost] : " input <&1
    dbhost=$(d "$input" "$dbhost")

    dbport=$(d "$dbport" 3309)
    read -p "Port (required) [$dbport] : " input <&1
    dbport=$(d "$input" "$dbport")

    [ -z "$dbsocket" -a -r /var/run/mysqld/mysqld.sock ] && dbsocket=/var/run/mysqld/mysqld.sock
    [ -z "$dbsocket" -a -r /tmp/mysqld.sock ] && dbsocket=/tmp/mysqld.sock
    read -p "Socket (required PHP=>5.5) [$dbsocket] : " input <&1
    dbsocket=$(d "$input" "$dbsocket")

    dbuser=$(d "$dbuser" root)
    read -p "User (required) [$dbuser] : " input <&1
    dbuser=$(d "$input" "$dbuser")

    dbpas1=x
    while [ "$dbpass" != "$dbpas1" ]; do
        read -p 'Password : ' dbpass <&1
        read -p 'repeat   : ' dbpas1 <&1
    done

    dbname=$(d "$dbname" pvlng)
    echo "Database MUST still exist, create it now if not!"
    read -p "Database (required) [$dbname] : " input <&1
    dbname=$(d "$input" "$dbname")

    e 'Please check your inputs/defaults'
    echo "Server   : $dbhost"
    echo "Port     : $dbport"
    echo "Socket   : $dbsocket"
    echo "User     : $dbuser"
    echo "Password : $dbpass"
    echo "Database : $dbname"
    read -p 'All correct? [Y/n] ' ok <&1
    [ -z "$ok" -o "$ok" == y ] && ok=Y

done

params="-h $dbhost -P $dbport -u $dbuser"

[ "$dbsocket" ] && params="$params -S $dbsocket"

e 'Import SQL definitions from sql/pvlng.sql ...'

mysql $params --password="$dbpass" $dbname <$PWD/sql/pvlng.sql

e 'Prepare config/config.yaml and set database credentials'

sed -e "s~<HOST>~$dbhost~g"     -e "s~<PORT>~$dbport~g" \
    -e "s~<SOCKET>~$dbsocket~g" -e "s~<USERNAME>~$dbuser~g" \
    -e "s~<PASSWORD>~$dbpass~g" -e "s~<DATABASE>~$dbname~g" \
    $PWD/config/config.default.yaml >$PWD/config/config.yaml

e 'All done.'

set +x
