--
-- v2.4.0 -> v2.5.0
--

DELETE FROM `pvlng_babelkit` WHERE `code_set` = 'preset' AND `code_code` = '60i';

REPLACE INTO `pvlng_babelkit` (`code_set`, `code_lang`, `code_code`, `code_desc`) VALUES
('app', 'de', 'DeleteReadingConfirm', 'Willst Du diesen Messwert wirklich löschen?!'),
('app', 'en', 'DeleteReadingConfirm', 'Do you really want delete this reading value?!'),
('app', 'de', 'ReadingDeleted', 'Messwert wurde gelöscht'),
('app', 'en', 'ReadingDeleted', 'Reading data deleted'),
('app', 'de', 'UseNegativeColor', 'Farbe für Werte unterhalb Grenzwert'),
('app', 'en', 'UseNegativeColor', 'Color for values below threshold'),
('app', 'de', 'below', 'unter'),
('app', 'en', 'below', 'below'),
('app', 'de', 'LineLongDashDotDot', 'Strich-Punkt-Punkt'),
('app', 'en', 'LineLongDashDotDot', 'dash-dot-dot'),
('app', 'de', 'LinesDashed', 'getrichelt'),
('app', 'de', 'LinesDotted', 'gepunktet'),
('app', 'de', 'LinesDashedDottedDotted', 'Strich-Punkt-Punkt'),
('app', 'en', 'LinesDashedDottedDotted', 'dash-dot-dot'),
('app', 'de', 'LinesDashedDotted', 'Strich-Punkt'),
('app', 'en', 'LinesDashedDotted', 'dash-dot'),
('app', 'en', 'LinesDotted', 'Dotted'),
('app', 'en', 'LinesDashed', 'Dashed'),
('app', 'de', 'LineLongDash', 'gestrichelt lang'),
('app', 'en', 'LineLongDash', 'dashed long'),
('app', 'de', 'LineShortDashDotDot', 'Strich-Punkt-Punkt kurz'),
('app', 'en', 'LineShortDashDotDot', 'dash-dot-dot short'),
('app', 'de', 'LineShortDashDot', 'Strich-Punkt kurz'),
('app', 'en', 'LineShortDashDot', 'dash-dot short'),
('app', 'de', 'LineShortDot', 'gepunktet kurz'),
('app', 'en', 'LineShortDot', 'dotted short'),
('app', 'de', 'LineShortDash', 'gestrichelt kurz'),
('app', 'en', 'LineShortDash', 'dashed short'),
('app', 'de', 'LineLongDashDot', 'Strich-Punkt lang'),
('app', 'en', 'LineLongDashDot', 'dash-dot long'),
('app', 'de', 'LineDashDot', 'Strich-Punkt'),
('app', 'en', 'LineDashDot', 'dash-dot'),
('app', 'de', 'LineDot', 'gepunktet'),
('app', 'en', 'LineDot', 'dotted'),
('app', 'de', 'LineDash', 'gestrichelt'),
('app', 'en', 'LineDash', 'dashed'),
('app', 'de', 'LineSolid', 'durchgezogen'),
('app', 'en', 'LineSolid', 'solid'),
('app', 'de', 'ChartTypeHint', 'Linen-Diagramme sind etwas schneller als Splines, aber Splines sind gleichmäßiger'),
('app', 'en', 'ChartTypeHint', 'Line charts are a bit faster than a slines, but splines are smoother'),
('app', 'de', 'ScatterChart', 'Punkte'),
('app', 'en', 'ScatterChart', 'Scatter'),
('app', 'de', 'BarChart', 'Balken'),
('app', 'en', 'BarChart', 'Bar'),
('app', 'de', 'AreaSplineChart', 'Spline mit Bereich'),
('app', 'en', 'AreaSplineChart', 'Spline with area'),
('app', 'de', 'AreaSplineRangeChart', 'Spline mit min./max. Bereich'),
('app', 'en', 'AreaSplineRangeChart', 'Spline with min./max. range'),
('app', 'de', 'SplineChart', 'Spline'),
('app', 'en', 'SplineChart', 'Spline'),
('app', 'de', 'LineChart', 'Linie'),
('app', 'en', 'LineChart', 'Line'),
('app', 'de', 'MarkAllHint', 'Kann nur für Balken-Diagramme verwendet werden (und macht nur dort Sinn)'),
('app', 'en', 'MarkAllHint', 'Can only be used (and makes only sense) for Bar charts'),
('app', 'de', 'MarkAll', 'alle'),
('app', 'en', 'MarkAll', 'all'),
('app', 'de', 'MarkLast', 'letzter'),
('app', 'en', 'MarkLast', 'last'),
('app', 'de', 'MarkMax', 'max.'),
('app', 'en', 'MarkMax', 'max.'),
('app', 'de', 'MarkMin', 'min.'),
('app', 'en', 'MarkMin', 'min.'),
('channel', 'de', 'resolutionHint', 'Beim Auslesen wird der gespeicherte/berechnete Messwert mit diesem Faktor multipliziert.'),
('channel', 'en', 'resolutionHint', 'On data readout the stored/calculated reading will multiplied with this factor'),
('preset', 'en', 'i', '::Minutes::'),
('app', 'de', 'AddOneToManyChannels', 'Einen oder mehrere Kanäle zur Hierarchie hinzufügen'),
('app', 'en', 'AddOneToManyChannels', 'Add one ore more channels to hierarchy'),
('app', 'de', 'DeleteReading', 'Messwert löschen'),
('app', 'en', 'DeleteReading', 'Delete reading value'),
('app', 'en', 'Add', 'Add');
