--
-- For development branch only!
--

REPLACE INTO `v_babelkit_changed` (`code_set`, `code_lang`, `code_code`, `code_desc`) VALUES
('app', 'de', 'MarkExtremes', 'Markiere Messwerte'),
('app', 'en', 'MarkExtremes', 'Mark reading values'),
('app', 'de', 'lastone', 'letzter'),
('app', 'en', 'lastone', 'last'),
('app', 'de', 'UseOwnConsolidation', 'Benutze einen eigenen Verdichtungzeitraum\r\n(Dieser wird aber nicht in den Varianten-Einstellungen gespeichert)'),
('app', 'en', 'UseOwnConsolidation', 'Use your own consolidation period\r\n(But this will not saved in variant settings)'),
('preset', 'de', '-', 'Verdichtung?'),
('preset', 'en', '-', 'Consolidation?'),
('preset', 'de', '2i', '2 Minuten'),
('preset', 'en', '2i', '2 Minutes'),
('preset', 'de', '2m', '2 Monate'),
('preset', 'de', '2q', '2 Quartale'),
('preset', 'de', '2w', '2 Wochen'),
('preset', 'de', '4h', '4 Stunden'),
('preset', 'de', '6h', '6 Stunden'),
('preset', 'de', '7d', '7 Tage'),
('preset', 'de', '8h', '8 Stunden'),
('preset', 'de', '20i', '20 Minuten'),
('preset', 'de', '30i', '30 Minuten'),
('preset', 'de', '60i', '60 Minuten'),
('preset', 'en', '2m', '2 Month'),
('preset', 'en', '2q', '2 Quarters'),
('preset', 'en', '2w', '2 Weeks'),
('preset', 'en', '4h', '4 Hours'),
('preset', 'en', '6h', '6 Hours'),
('preset', 'en', '7d', '7 Days'),
('preset', 'en', '8h', '8 Hours'),
('preset', 'en', '20i', '20 Minutes'),
('preset', 'en', '30i', '30 Minutes'),
('preset', 'en', '60i', '60 Minutes'),
('preset', 'de', '2h', '2 Stunden'),
('preset', 'de', '12h', '12 Stunden'),
('preset', 'de', '14d', '14 Tage'),
('preset', 'en', '2h', '2 Hours'),
('preset', 'en', '12h', '12 Hours'),
('preset', 'en', '14d', '14 Days'),
('preset', 'de', '1d', '1 Tag'),
('preset', 'de', '1h', '1 Stunde'),
('preset', 'de', '1m', '1 Monat'),
('preset', 'de', '1q', '1 Quartal'),
('preset', 'de', '1w', '1 Woche'),
('preset', 'de', '1y', '1 Jahr'),
('preset', 'de', '10y', 'Dekade'),
('preset', 'en', '1d', '1 Day'),
('preset', 'en', '1h', '1 Hour'),
('preset', 'en', '1m', '1 Month'),
('preset', 'en', '1q', '1 Quarter'),
('preset', 'en', '1w', '1 Week'),
('preset', 'en', '1y', '1 Year'),
('preset', 'en', '10y', 'Decade'),
('preset', 'de', '10i', '10 Minuten'),
('preset', 'en', '10i', '10 Minutes'),
('code_set', 'de', 'preset', 'Voreinstellung'),
('code_set', 'en', 'preset', 'Preset');
