--
-- v2.11.* > v2.12.0
--

UPDATE `pvlng_channel` SET `type` = 41 WHERE `type` = 40;
DELETE FROM `pvlng_type` WHERE `id` = 40;

INSERT INTO `pvlng_type` (`id`, `name`, `description`, `model`, `unit`, `type`, `childs`, `read`, `write`, `graph`, `icon`) VALUES
(6, 'Inverter string', 'model::Group', 'Channel', '', 'group', -1, 0, 0, 0, '/images/ico/solar-panel.png'),
(48, 'Solar Edge Inverter', 'model::SolarEdgeInverter', 'SE\\Inverter', '', 'group', -1, 0, 1, 0, '/images/ico/solar_edge.png'),
(49, 'Solar Edge Optimizer', 'model::SolarEdgeOptimizer', 'SE\\Optimizer', '', 'group', -1, 0, 1, 0, '/images/ico/solar_edge.png');

REPLACE INTO `pvlng_babelkit` (`code_set`, `code_lang`, `code_code`, `code_desc`, `code_order`) VALUES
('app', 'de', 'Decimals', 'Dezimalstellen', 0),
('app', 'de', 'DeleteEntityHint', 'Kanal löschen (nur möglich, wenn nicht in der Kanal-Hierarchie verwendet)', 0),
('app', 'en', 'DeleteEntityHint', 'Delete channel (only possible if not assigned in channel hierarchy)', 0),
('app', 'de', 'UsableInCharts', 'Kann in Diagrammen angezeigt werden', 0),
('app', 'en', 'UsableInCharts', 'Usable in charts', 0),
('app', 'en', 'Decimals', 'Decimals', 0),
('app', 'de', 'Template', 'Vorlage', 0),
('app', 'en', 'Template', 'Template', 0),
('app', 'de', 'AdjustTemplate', 'Vorlage anpassen', 0),
('app', 'en', 'AdjustTemplate', 'Adjust template', 0),
('app', 'de', 'Weather', 'Wetter', 0),
('app', 'en', 'Weather', 'Weather', 0),
('app', 'de', 'WeatherForecast', 'Wettervorhersage', 0),
('app', 'en', 'WeatherForecast', 'Weather forecast', 0),
('app', 'de', 'Clouds', 'Wolken', 0),
('app', 'en', 'Clouds', 'Clouds', 0),
('app', 'de', 'AliasCreated', 'Alias-Kanal erstellt', 0),
('app', 'en', 'AliasCreated', 'Alias channel created', 0),
('app', 'de', 'ConfirmDeleteTreeNode', 'Löscht den Kanal aus dem Baum.\r\n\r\nBist Du sicher?', 0),
('app', 'en', 'ConfirmDeleteTreeNode', 'Delete channel from tree.\r\n\r\nAre you sure?', 0),
('app', 'de', 'ConfirmDeleteTreeItems', 'Löscht den Kanal (und eventuelle Sub-Kanäle) aus dem Baum.\r\n\r\nBist Du sicher?', 0),
('app', 'en', 'ConfirmDeleteTreeItems', 'Delete channel (and may be all sub channels) from tree.\r\n\r\nAre you sure?', 0),
('app', 'de', 'ClickDragShiftPan', 'Klicken und ziehen zum Vergrößern, Shift-Taste drücken und Klicken zum Verschieben.', 0),
('app', 'en', 'ClickDragShiftPan', 'Click and drag to zoom in, hold down shift key and click to pan.', 0),
('app', 'en', 'Resolution', 'Factor', 0),
('app', 'de', 'Resolution', 'Faktor', 0),
('app', 'de', 'CacheMisses', 'Fehlschläge', 0),
('app', 'en', 'CacheMisses', 'Misses', 0),
('app', 'de', 'CacheHits', 'Treffer', 0),
('app', 'en', 'CacheHits', 'Hits', 0),
('app', 'de', 'Cache', 'Cache', 0),
('app', 'en', 'Cache', 'Cache', 0),
('app', 'de', 'Key', 'Schlüssel', 0),
('app', 'en', 'Key', 'Key', 0),
('app', 'de', 'OnlyChannelsWithReadings', 'Nur Kanäle mit Messwerten', 0),
('app', 'en', 'OnlyChannelsWithReadings', 'Only channels with readings', 0),
('model', 'de', 'Dashboard_thresholdHint', 'Wenn angegeben, werden Messwerte (Zahlen) unterhalb in rot und oberhalb in grün ausgegeben.', 0),
('model', 'en', 'Dashboard_thresholdHint', 'If defined, reading values (numbers) below this will be colored red, above green.', 0),
('app', 'en', 'EditSwitchAliasWithOriginal', 'You can\'t edit an alias, therefor switch to original channel!', 0),
('app', 'de', 'EditSwitchAliasWithOriginal', 'Du kannst keinen Alias bearbeiten, deshalb Wechsel zum Original-Kanal!', 0),
('model', 'de', 'SolarEstimate_extraHint', 'Anzahl der Tage in der Vergangenheit, die zur Berechnung herangezogen werden sollen.', 0),
('model', 'en', 'SolarEstimate_extraHint', 'Count of days in the past to be used for calulation.', 0),
('model', 'en', 'SolarEstimate_extra', 'Days', 0),
('model', 'de', 'SolarEstimate_extra', 'Tage', 0),
('app', 'de', 'UseDifferentColor', 'Abweichende Farbe ab Grenzwert', 0),
('app', 'en', 'UseDifferentColor', 'Different color from threshold', 0),
('app', 'en', 'above', 'above', 0),
('app', 'de', 'above', 'über', 0),
('app', 'de', 'MoreIntoBackground', 'weiter nach hinten', 0),
('app', 'en', 'MoreIntoBackground', 'more to back', 0),
('app', 'en', 'MoreIntoForeground', 'more to front', 0),
('app', 'de', 'MoreIntoForeground', 'weiter nach vorn', 0),
('app', 'en', 'ChartPositionHint', 'The channels are displayed in the chart by default in the same order as in the channels overview list.\r\nHere you can move them more to back/front.\r\n', 0),
('app', 'de', 'ChartPositionHint', 'Normalarweise werden die Kanäle in der Reihenfolge im Diagramm angezeigt, in der sie in der Kanalübersicht aufgelistet sind.\r\nHier können die Kanäle abweichend davon weiter nach hinten/vorn verschoben werden.', 0),
('app', 'de', 'ChartPosition', 'Diagrammposition', 0),
('app', 'en', 'ChartPosition', 'Chart position', 0),
('model', 'en', 'Averageline_extra', 'Calculation mode', 0),
('model', 'de', 'Averageline_extra', 'Berechnungsmodus', 0),
('model', 'de', 'Averageline_extraHint', 'Das Harmonische Mittel glättet Spitzen, z.B. für Stromverbrauchs-Kanäle', 0),
('model', 'en', 'Averageline_extraHint', 'The harmonic mean smooth peaks, e.g. for power consumption channels', 0),
('model', 'en', 'Accumulator_extraHint', 'Only if all child channels have value the consolidation starts', 0),
('model', 'de', 'Accumulator_extra', 'Strikter Modus', 0),
('model', 'de', 'Accumulator_extraHint', 'Erst wenn alle Sub-Kanäle Werte haben, wird zusammengefasst', 0),
('model', 'en', 'Accumulator_extra', 'Strict mode', 0),
('app', 'de', 'DatabaseFree', 'Freier Bereich', 0),
('app', 'en', 'DatabaseFree', 'Data free', 0),
('app', 'de', 'DatabaseSize', 'Datengrösse', 0),
('app', 'en', 'DatabaseSize', 'Data Length', 0),
('app', 'de', 'Database', 'Datenbank', 0),
('app', 'en', 'Database', 'Database', 0),
('model', 'de', 'DatabaseUsage_extraHint', 'Funktioniert für die numerischen und die alphanumerischen Messwerte', 0),
('model', 'en', 'DatabaseUsage_extraHint', 'Works for the numeric and the non-numeric readings', 0),
('model', 'de', 'DatabaseUsage_extra', 'Messwerte-Typ', 0),
('model', 'en', 'DatabaseUsage_extra', 'Readings type', 0),
('model', 'de', 'Wunderground', 'Multi sensor für die [url=http://www.wunderground.com]Weather Underground API[/url]', 0),
('model', 'en', 'Wunderground', 'Multi sensor for [url=http://www.wunderground.com]Weather Underground API[/url]', 0),
('model', 'de', 'OpenWeatherMap', 'Multi sensor für die [url=http://openweathermap.org/]OpenWeatherMap API[/url]', 0),
('model', 'en', 'OpenWeatherMap', 'Multi sensor for [url=http://openweathermap.org/]OpenWeatherMap API[/url]', 0),
('model', 'de', 'MeterToSensor', 'Berechnet Sensor-Daten aus einem Meter-Kanal in Abhängigkeit der Zeitdifferenz zwischen den Messwerten', 0),
('model', 'en', 'MeterToSensor', 'Calculates sensor data from a meter channel depending of the time difference between the readings', 0),
('model', 'de', 'Daylight', 'Zeigt entweder Marker für Sonnauf- und untergang oder eine Kurve zwischen Sonnauf- und untergang (erfordert einen Einstahlungssensor-Kanal)', 0),
('model', 'en', 'Daylight', 'Show either markers for sunrise / sunset or a curve between sunrise and sunset (requires a irradiation sensor channel)', 0),
('app', 'de', 'ChannelTypes', 'Kanaltypen', 0),
('app', 'en', 'ChannelTypes', 'Channel types', 0),
('app', 'de', 'ShowDescription', 'Beschreibung anzeigen', 0),
('app', 'en', 'ShowDescription', 'Show description', 0),
('channel', 'de', 'latitudeHint', 'Breitengrad des Standortes\r\nStandard ist Norden, gib einen negativen Werte für Süden ein\r\n(Finde Deine Koordinaten auf [url=http://de.mygeoposition.com/]MyGeoPosition.com[/url])', 0),
('channel', 'de', 'longitudeHint', 'Längengrad des Standortes\r\nStandard ist Osten, gib einen negativen Werte für Westen ein', 0),
('channel', 'en', 'latitudeHint', 'Latitude of location\r\nDefaults to North, use negative value for South\r\n(Find your coordinates on [url=http://en.mygeoposition.com/]MyGeoPosition.com[/url])', 0),
('channel', 'en', 'longitudeHint', 'Longitude of location\r\ndefaults to East, use negative value for West', 0),
('model', 'de', 'Daylight_resolutionHint', 'Anzeige als Sonnenaufgangs/-untergangs-Marker oder als Kurve über die Zeit', 0),
('model', 'de', 'Daylight_timesHint', 'Zeige auch die Uhrzeit für Sonnenaufgang und -untergang\r\n(Nur für Anzeige als [b]Marker[/b])', 0),
('model', 'de', 'Daylight_times', 'Zeige Uhrzeit', 0),
('model', 'en', 'Daylight_times', 'Show time', 0),
('model', 'en', 'Daylight_timesHint', 'Show also the sunrise/sunset time\r\n(Only for display as [b]Marker[/b])', 0),
('locale', 'en', 'Date', 'd/M/Y', 0),
('locale', 'en', 'DateDefault', 'd/M/Y', 0);
